### ISSUE TITLE
New landing page on master

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/Tutorials#10]
We can use master to document the existing tutorials and provide a link. I'm opening this issue to document and host discussion on this redesign.

**Comment by EiffL** [comment]
@sfarrens I have put a proposed redesign of the master branch on branch `issue/10`:

https://github.com/CosmoStat/Tutorials/tree/issue/10

I think we could also have a small blurb on each tuto to help people navigate. I'm not sure also of where to put the binder button.

And checkout the format of the tutorials we built for data access in lsst desc:
https://github.com/LSSTDESC/DC2-analysis/blob/master/tutorials/README.rst

**Comment by santiagocasas** [comment]
I like how you have in DESC the ipynbs without output and the rendered ones using nbviewer. That could be useful for us too. Do we need beavis-ci for that or can we (should we) do it manually?

**Comment by EiffL** [comment]
Well. hummmm. Yeah we could have in each section for each tutorial a link to the notebooks of these tutorials.  I didn't think of that.....
But otherwise, we can always have a binder or colab link for each tutorial, it's even cooler than an nbviewer link

**Comment by santiagocasas** [comment]
yeah, the only problem with binder is that it takes a while to load, but sure, this is what we had already. With Colab, I think I encountered some problems for the Cosmo tutorials that need cosmo packages like camb or class, but that was a while ago, maybe now it works fine and their pip installation can be used.

**Comment by EiffL** [comment]
@sfarrens @santiagocasas I've made a proposed modification to the README. I'm not super happy with the fact that it's not super compact. But I added sweet badges and shields ;-D 
Checkout #15

**Comment by sfarrens** [comment]
Looks pretty cool to me (I ❤️badges). 

I am a bit confused as to why "Introduction to Python" links to the  python branch and "Tutorial 1: Beginner Topics" and "Tutorial 2: Intermediate and Advanced Topics" link to the master branch.

**Comment by EiffL** [comment]
I'm lacking the face palm emoji on github..... hold on

**Comment by EiffL** [comment]
ok, fixed :-)

**Comment by EiffL** [comment]
Ok sweet, thanks both for the discussion.... annnnd check this out:
@all-contributors please add @sfarrens for code, content, and ideas

**Comment by EiffL** [comment]
Also, @all-contributors please add @santiagocasas for code, content, and ideas
