### ISSUE TITLE
TensorFlow Tutorial

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/Tutorials#11]
I'm opening this issue to document the preparation of a new TensorFlow tutorial, in collaboration with @zaccharieramzi

**Comment by EiffL** [comment]
We (and by we I mean @zaccharieramzi ) are starting work on this tutorial in branch `tensorflow-tutorial`.

**Comment by EiffL** [comment]
@zaccharieramzi I have added a draft of a codelab, it's being hosted, through some submodule magic here:
https://cosmostat.github.io/Tutorials/tensorflow-introduction/tensorflow-introduction/#0
I haven't found a perfect solution yet to get rid of this repetition of `tensorflow-introduction` in the path :-/

I have taken some very sparse notes on how to build this here: https://github.com/CosmoStat/Tutorials/blob/tensorflow-tutorial/codelab_notes.txt

But essentially, all you have to do is install CLAAT (CodeLab As A Thing) one way or another... or even just use a docker container https://github.com/zenika-open-source/claat-image
and then run:
```
$ claat export tutorial.md
```
then you can also serve the codelab locally with
```
$ claat serve -addr 0.0.0.0:9090 tutorial.md
```

The codelab itself is just this `tutorial.md` file, the specific formatting to use can be found here: https://github.com/googlecodelabs/tools/tree/master/claat/parser/md

And here is a great codelab example that I wll try to take inspiration from: https://codelabs.developers.google.com/codelabs/cloud-tensorflow-mnist/#0
Just to see how they structure it

**Comment by zaccharieramzi** [comment]
Super cool @EiffL !!!

**Comment by sfarrens** [comment]
I think you can close this issue now.

**Comment by sfarrens** [comment]
Tutorial available in https://github.com/CosmoStat/Tutorials/tree/tensorflow-tutorial
