### ISSUE TITLE
Introduction to MCMC and Bayesian inference

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/Tutorials#12]
In this proposed tutorial we plan to explain the following points:
 - What is a likelihood function
 - What is a prior
 - What is a posterior
 - What is an MCMC chain
 - How to use emcee to fit some function

Other things ?

**Comment by sfarrens** [comment]
@EiffL are you proposing to give this tutorial yourself?

**Comment by EiffL** [comment]
Sure. I can actually give it this Friday, if the expected level is low enough, and if there is a demand for it.

**Comment by EiffL** [comment]
(like simply explaining what is a likelihood, a prior, and how an MCMC works)

**Comment by sfarrens** [comment]
@EiffL When would you rather give this tutorial?
- [x] 26th of June
- [ ] 3rd of July
- [ ] 10th of July
- [ ] 17th of July
- [ ] 25th of July
- [ ] Sometime in September

**Comment by EiffL** [comment]
sure let's do june 26th

**Comment by sfarrens** [comment]
@EiffL Gentle reminder to add tutorial materials. 

Here is your YouTube badge: [![youtube](https://img.shields.io/badge/-youtube-red?logo=youtube&labelColor=grey)](https://www.youtube.com/watch?v=EfWEGBHeA3k)

**Comment by EiffL** [comment]
:-| ..... I didn't do that? Past me is just the worst!

**Comment by EiffL** [comment]
And here is the notebook I managed to recover:
https://colab.research.google.com/drive/1EUF7-CwamhAT6wedntStdb4x3dDbihoo?usp=sharing
