### ISSUE TITLE
Distributing software through containers

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/Tutorials#13]
This tutorial aims to demonstrate how to distribute your software in Docker. Please comment here if there are specific things you want know,

**Comment by sfarrens** [comment]
Reminder this tutorial is planned for the learning slot on Friday 15/05/20.

**Comment by EiffL** [comment]
@fadinammour suggested to use his Octave tutorial as an example of how to use Docker to package dependencies, I think it's a great idea!
https://github.com/CosmoStat/octave_image_processing_example

**Comment by sfarrens** [comment]
Tutorial available in https://github.com/CosmoStat/Tutorials/tree/docker
