### ISSUE TITLE
Introduction to Unix (basic commands and shell scripting)

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/Tutorials#14]
This tutorial should provide the basics of how to do stuff on unix. @fadinammour should provide mode details ;-)

**Comment by sfarrens** [comment]
@fadinammour Are you still interested in organising this tutorial?

**Comment by fadinammour** [comment]
@sfarrens Yes sir! Julien shared this nice source with me https://missing.csail.mit.edu/
Is there any deadline or schedule? I would like to prepare it a bit in advance

**Comment by sfarrens** [comment]
@fadinammour OK great, just choose a date that suits you and we will reserve it for this tutorial.

**Comment by fadinammour** [comment]
The 19th of June is OK for me (or any other day after this one).

**Comment by sfarrens** [comment]
OK, I have put you down for the 19th.

**Comment by sfarrens** [comment]
@all-contributors add @fadinammour for ideas and content

**Comment by sfarrens** [comment]
@all-contributors add @JulienNGirard for content

**Comment by sfarrens** [comment]
Tutorial added in #49

**Comment by JulienNGirard** [comment]
Hey thanks :) but I only did the part on Screen, most work has been done by Fadi.
