### ISSUE TITLE
[Tutorial] Tips for presentations

### ISSUE THREAD

**Issue by pettorin** [CosmoStat/Tutorials#36]
**What is the main topic of this tutorial**: [Please provide one/two words, e.g. python, sparsity, etc.] Presentations, slides

**One line description**
[Please describe here what you would hope to learn/teach]
I can review tips to prepare talks, slides and story-telling, based on what I learned so far. 

**Level**
- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Learning goals**
[Please give here a few clear learning goals]
  - Being aware of the who/where/why/what/how when preparing a talk
  - Quick tips to improve slides and some possible misconceptions

**Comment by sfarrens** [comment]
@all-contributors add @pettorin for ideas and content

**Comment by sfarrens** [comment]
Tutorial added in #43
