### ISSUE TITLE
[Tutorial] Blind source separation

### ISSUE THREAD

**Issue by RCarloniGertosio** [CosmoStat/Tutorials#46]
**What is the main topic of this tutorial**: blind source separation

**One line description**
This tutorial should provide with the basics of blind source separation (PCA, ICA, NMF, SMF, etc.), with a focus on GMCA.

**Level**
- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Learning goals**
To be determined

**Comment by RCarloniGertosio** [comment]
My priority right now is to finish writing an article. I will then prepare the tutorial, which should be ready by **mid-July**.

**Comment by sfarrens** [comment]
@RemiCG How about the 31st of July? This should give you a bit of a buffer. Otherwise, we can find a date in September.

**Comment by RCarloniGertosio** [comment]
@sfarrens Let's set that date. I will let you know if I am ready before or if I need more time.

**Comment by sfarrens** [comment]
Added in #63

**Comment by sfarrens** [comment]
@all-contributors add @RCarloniGertosio for content
