### ISSUE TITLE
[Tutorial] Python Packaging Template

### ISSUE THREAD

**Issue by sfarrens** [CosmoStat/Tutorials#62]
**What is the main topic of this tutorial**: Python

**One line description**
This tutorial will present a standardised template for packaging Python codes.

**Level**
- [x] Beginner
- [x] Intermediate
- [ ] Advanced

**Learning goals**
  - How to prepare API documentation
  - How to run automated CI/CD tests
  - How to check code quality and unit test coverage
  - How to deploy packages on PyPi

**Comment by sfarrens** [comment]
Proposed date of tutorial: **11/12/2020**

**Comment by EiffL** [comment]
We've done that, right? (last year is already a blur >.<)
