### ISSUE TITLE
[Tutorial] How to compute lensing Cells from a map and compare it to theory

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/Tutorials#67]
**What is the main topic of this tutorial**: Learning about power spectra and how they are computed.

**One line description**
Present how one can compute a power spectrum from a lensing map (in the flat sky approximation) from simulations, how to compute the corresponding theory spectrum, and maybe how to generate a Gaussian realisation with the same power spectrum.

**Level**
- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Learning goals**
[Please give here a few clear learning goals]
  - How to compute a power spectrum using an FFT
  - How to convert frequencies to angular multipoles \ell
  - How to use a cosmology code to compute a theoreticel angular Cell

With @b-remy and @dlanzieri we have a first draft of an example notebook that go over these points.

**Comment by sfarrens** [comment]
@EiffL Do you have a date in mind for this tutorial?

**Comment by EiffL** [comment]
Not yet.... TBD But it can be pretty soon, maybe next week?

**Comment by EiffL** [comment]
But I should say.... That's up to Benjamin and Denise ^^'

**Comment by sfarrens** [comment]
@b-remy @dlanzieri does next week work for you or would you prefer a bit more time to prepare?

**Comment by b-remy** [comment]
Hi @sfarrens, we agreed to present this tutorial this week :)

**Comment by sfarrens** [comment]
OK, I will reserve 22/01/21 at 14:00 for this tutorial

**Comment by EiffL** [comment]
We can almost close this :-) Would one of you have time to open a Pull Request adding a link to the tutorial in the README file? You can have a look for instance at how the TensorFlow tutorial is linked to in the current readme

**Comment by EiffL** [comment]
Woups, we forgot one step, @all-contributors please add @b-remy and @dlanzieri for content
