### ISSUE TITLE
[AAA] Git

### ISSUE THREAD

**Issue by sfarrens** [CosmoStat/Tutorials#69]
**What is the main topic of this session**: Git

**Would you like to invite an external expert for this session?**:

- [X] Yes
- [ ] No

**Proposed expert(s):**  [Valentin Haenel](https://github.com/esc)

Software engineer @ Anaconda. Working on Numba, Blosc and others.

**Possible dates for AAA session:** 26/03/21

**Comment by esc** [comment]
I am the volunteer! Friday 5th of March 14:00 CET works well for me as do most other Fridays.

**Comment by sfarrens** [comment]
Thanks again @esc, we very much appreciate your time. I will ask the students to let me know if there is a specific Friday where most of them can attend so that we can take advantage.

Next Friday won't be possible because we are organising a [machine learning day for astrophysics](http://www.cosmostat.org/events/learning-in-astrophysics-2021), but other than that any Friday should work. I will get back to you ASAP.

**Comment by santiagocasas** [comment]
thanks @sfarrens  and @esc , this is great!!  I think for me every Friday is fine, except Friday 19th March (conference).

**Comment by esc** [comment]
OK, Friday 12 won't be possible for me. How about the 26th then?

**Comment by esc** [comment]
(Friday 26 March 2021) 😉

**Comment by esc** [comment]
I'll pencil it in for now.

**Comment by sfarrens** [comment]
Hi @esc, it looks like 26/03/21 works for everyone so we can got ahead and fix this date.

I will send you a zoom link on the day shortly before 14:00 CET. As I mentioned on Twitter you don't need to prepare anything unless you want to. In general, we try to keep these sessions quite informal and leave as much time as possible for students to ask questions.

Regarding Git, I would say the experience in team is varied. There are some people that have quite a bit of experience and others that have only started using it this year.

Let me know if you have any questions about these sessions or anything else beforehand. Thanks again! 😄

**Comment by esc** [comment]
@sfarrens thank you for tye confirmation and information, look forward to seeing you all then.

**Comment by sfarrens** [comment]
Hi @esc! Just a reminder that we have your learning slot on Git scheduled for tomorrow (26/03/21) at 14:00 CET. I will send you a zoom link shortly beforehand (on Twitter?). I will ask you to introduce yourself at the beginning of the session and then whenever someone from the team asks a question I will ask them to introduce themselves also.

Let me know if you have any questions. 🙂

**Comment by esc** [comment]
@sfarrens excellent! Yes, Twitter is fine, or we can exchange emails via Twitter DM? We will find a way. Am very much looking forward to this and have a short introduction prepped and ready to go. See you soon!

**Comment by sfarrens** [comment]
## Notes from today's session

### Commit history
- `git log --oneline --graph --decorate --all`

### Handling Jupyter notebooks
- [nbstripout](https://github.com/kynan/nbstripout)
- [nbdime](https://github.com/jupyter/nbdime)
- [jupytext](https://github.com/mwouts/jupytext)

### Mirroring
- `git clone` [mirroring option](https://stackoverflow.com/questions/3959924/whats-the-difference-between-git-clone-mirror-and-git-clone-bare)
- Not to be confused with [GitLab repository mirroring](https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html)

### Z shell
- https://ohmyz.sh/

### Rebase or merge?
- Rebase -> linear history
- Merge -> more information on when branches were made and why
- [Directed acyclic graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph)
