### ISSUE TITLE
Create a template for new tutorials

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/Tutorials#9]
One or two branches in the repo can be templates for starting a new binder or new colab tutorial, with a readme, example notebook, example environment file.

**Comment by EiffL** [comment]
@santiagocasas @sfarrens check this out: https://github.com/CosmoStat/Tutorials/issues/new/choose
Let me know if there is anything you would like to change to this templace

**Comment by sfarrens** [comment]
Very cool @EiffL! I would recommend adding something like: 

**Level**
- [X] Beginner
- [ ] Intermediate
- [ ] Advanced

Also I think you need to fix the spaces with the `**`.

**Comment by sfarrens** [comment]
We could also add issue templates for bugs fixes _etc._ for existing tutorials. I have  some [templates](https://github.com/CEA-COSMIC/ModOpt/issues/new/choose) I already prepared for ModOpt.

**Comment by EiffL** [comment]
ouh, yes yes yes ok, let me add the level section, and fix formatting. Go nuts if you want to add a bug report template :-D

**Comment by sfarrens** [comment]
I added templates for bugs and general help.

**Comment by EiffL** [comment]
great :-D I have added a link to propose a new tutorial directly from the main Readme in #23

**Comment by EiffL** [comment]
Cool beans, I think we are good on that issue. Thanks !
